services:
  db:
    image: mariadb:10.6 
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword123
    volumes:
      - mysql_data:/var/lib/mysql
      - upload_data:/data
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: app_flask
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_APP: __init__.py
      FLASK_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppassword123
      SECRET_KEY: ta_cle_secrete_ici
    volumes:
      - .:/app
      - ./logs:/logs
      - upload_data:/app/static/uploads  # ✅ On monte le volume ici en écriture pour les logos
    ports:
      - "8073:5000"
    networks:
      - app_network

  phpmyadmin:
      image: phpmyadmin
      container_name: app_phpmyadmin
      restart: unless-stopped
      ports:
        - "8081:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      networks:
        - app_network

volumes:
  mysql_data:
  upload_data:  # ✅ Déclaration indispensable du volume ici

networks:
  app_network:
    driver: bridge